FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809
COPY . c:/temp/
WORKDIR c:/temp/
RUN dotnet.exe publish splitNspSharpGui.Wpf -c contained -r win-x64
RUN dotnet.exe publish splitNspSharpGui.Wpf -c dependent -r win-x64
RUN dotnet.exe publish splitNspSharpGui.Wpf -c framework -r win-x64
ENTRYPOINT cmd.exe
