FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster
COPY . /temp/app/
WORKDIR /temp/app
RUN dotnet publish splitNspSharpGui.Gtk -c contained
RUN dotnet publish splitNspSharpGui.Gtk -c dependent
ENTRYPOINT /bin/bash
