FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster
COPY . /temp/app/
WORKDIR /temp/app
RUN dotnet publish splitNspSharp -c contained -r linux-x64
RUN dotnet publish splitNspSharp -c dependent -r linux-x64
ENTRYPOINT /bin/bash
